services:
  #获取权限
  "getElements":
    type: SPRING
    uri: "cn.gov.zcy.user.service.ZcyResourcePrivilegeReadService:getElements"
  #获取角色编码
  "getRoles":
    type: SPRING
    uri: "cn.gov.zcy.trade.service.PurchaseReadService:getRoles"
  #获取全站链接
  "getEnvHref":
    type: SPRING
    uri: cn.gov.zcy.user.service.ZcyResourcePrivilegeReadService:getEnvHref
  #获取区划
  "getMyDistrict":
    type: SPRING
    uri: cn.gov.zcy.user.service.agent.DistrictServiceAgent:getMyDistrict
